baseURL = "https://junghwan16.github.io/"
locale = "ko"
title = "조정환"
buildFuture = true
enableRobotsTXT = true

[params]
  description = "Backend Engineer"
  author = "조정환"
  github = "https://github.com/junghwan16"

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.extensions]
      table = true
      strikethrough = true
      taskList = true
      footnote = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["$$", "$$"]]
          inline = [["$", "$"]]

  [markup.highlight]
    codeFences = true
    noClasses = false

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[pagination]
  pagerSize = 30

[related]
  threshold = 80
  includeNewer = true
  toLower = true
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "date"
    weight = 10

[sitemap]
  changeFreq = "weekly"

[services]
  [services.rss]
    limit = 20

[outputs]
  home = ["HTML", "RSS"]
